apiVersion: ENC[AES256_GCM,data:bAY=,iv:ZlzZdqhJLWNCBgIp8ixNso0eLZWe6s5C/Y6QeKiEoiQ=,tag:OLwZWjzBULhrW4C5DtHO9Q==,type:str]
kind: ENC[AES256_GCM,data:7qttV+TK,iv:/GBL/sG/UUS9AtWhilAKXnNYKlsaAvF+l8vP7KFjCgs=,tag:fQnNGp5fyXOj6Thz77iM7g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:+vIvQPMBqdgOBuqp4lNkMcg=,iv:W3FngvUe4RDGWh1Cja4pgqJLlvjypiS+h9+rurodA1A=,tag:9hLNIeXwe/BAaINb2gXFkg==,type:str]
    namespace: ENC[AES256_GCM,data:TTkj5KTZIF7HjO0=,iv:YVBfFHzvnn6rziLhf2ZgA8oAHP/7zAID39wDp6TdA8s=,tag:sHZMH6JBUXxFNVL/PjHDtw==,type:str]
type: ENC[AES256_GCM,data:mvbOpVJW,iv:N45cTFCzYOi3qHW3ewixuwY1JVBDel3lYLykOzRvooU=,tag:xedspEMW10seQ5l7WDnkLw==,type:str]
data:
    api_key: ENC[AES256_GCM,data:KROAnLcJQU3wcTCxnhm1BAuM+jM=,iv:4O6ZaY4n9ZT/It77BkcuLYMzsCwNMfF+QYopmaLO8/4=,tag:JkDQN3FGSaCcVpE+Uh7ERA==,type:str]
    hello: ENC[AES256_GCM,data:tYeAPQHNCCXSN5bn,iv:61yVuyp/9sC/O3skoYw15k++zb+0A0Pc46GeELZiN6U=,tag:tg85TdtjL925YMKP7TKL2g==,type:str]
    password: ENC[AES256_GCM,data:LZGsBBCjDXxOX6/rUikObmHwAkE=,iv:u07omg9SC44ouxLDVr3hrOgJfeU+S4YerkoLjGIPaLY=,tag:ht94HbuaCuv7Z/ZZVmaYbg==,type:str]
    test: ENC[AES256_GCM,data:eCtTQw==,iv:otx1zhSzl5Yl5SG0vk2si/fuFQbFZEhR9HyRuCAapZA=,tag:a0Dt7bo20lsTLoF0NykkDw==,type:str]
    username: ENC[AES256_GCM,data:ogHYkYBk90yhIu7b,iv:KRs3PwHCQoTfjtMT5+sXDpKlCZSwMytFgmNTdBNFWX0=,tag:v69MMeCr+gXdZ9aRM3Rssw==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:000000000000:alias/sops-secrets
          created_at: "2026-03-27T02:36:10Z"
          enc: NDY3MWE1YWYtNDRhOC00YzE1LTllYzgtZmRkNWFmNGI0ZDM5H7znJXQhWPgg31dUDNYToftJaA57OaQijn6rubwtc8U+umnVW3dDP1R7+xyRANRmzO6X8vGnXB8QrwDDoqML8h5WKcGsXX8AYm8eZEMrmU0=
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v0kj30lq3ms08909fvlw4s7d667l822tnjlrgq628hp6jrsdnvzsearc33
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlN2pWSzNjcGx4dTlDWDAr
            YytQTFc0Qm10aFF3MkZvTVVIOS9FY2xHcVJRCjlYd0pDOVZkRGRmNzJYVTJ4UFJQ
            d3h5RXprOFFjRkFwWUdvNVJmY3krMGMKLS0tIDdJNU1UQ205UElxRHVoakllM2kr
            WWdzaStUM09PUHRuYTd1YjZXdUJ6c2sK44eiw69jASuEe8frU1rxW1TcPTa9wv+F
            qd47HjVUkB9wFqSP2jFhlUgoPR+xaVeKQOwbZZZnNAa/vdZHyvYkpw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-27T02:30:22Z"
    mac: ENC[AES256_GCM,data:Fy9VwKEboag3bBe5CHlDjdbPl8Fxj80wddAi3qg/Ca1bOdvPYMMjdBaedZ/Grfln/EyIWacgcd3TaF0tdTj7Xy6KC3Yk7aYmdXXDwheuojmlnALXPyLWEgpRPWDq0787QKMGaFkr/COtsCsItxclbuK/NyvMOpkktVGM7bZ3M9o=,iv:XZXAuEjCUY6E4N49fFiATnA0o+HWtIsxvJqJgBAk4C8=,tag:Vuf4IJLnsJjfq+eoMQ808Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.2
