apiVersion: ENC[AES256_GCM,data:HI4=,iv:6RFz6eDCWjlgItZ04zvLbQ8/dZYKVvjS2OaAp3PJI5w=,tag:9N6wtZWCGPEZdnjg2oe9lw==,type:str]
kind: ENC[AES256_GCM,data:96JKZoJW,iv:mn5ldi2mEx883aPzRbYLgZPXrE9Fp9Dn7QecpT+aJKk=,tag:kXUlmcX1cf0en1Jy2oLCzg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:jav7WBMWZ0Aan3SNHrw=,iv:1ONJbuqTH251dHJ5zTdeu6MtTwl0pnupE25UKcylQe0=,tag:Nlb7e7EGhtkz308wIjur0g==,type:str]
    namespace: ENC[AES256_GCM,data:rvufd7/fCNsW+AY=,iv:cvIGE2/ogkviiHKXNWu1/SMMBUamjKtO0oyGNcmfg+0=,tag:Ng+V1d/Q5hXHjGhAdIxSEw==,type:str]
type: ENC[AES256_GCM,data:ETI+Ji2I,iv:vAT6n2rBPu83bJfxH1+YtzHsEOInTUlJJ9OfoImbvlA=,tag:4eEI926JACW61/5mP4oqjg==,type:str]
data:
    DB_HOST: ENC[AES256_GCM,data:x3IMYX7mNQATJmJFR2as3uzQC9KaQLpmqNat4Lc62jXw6Aku7mqfsw==,iv:KBHDpxcb5Q6eIgN9G/u1hFRpbm4oxGA/MZ2bIlqJ730=,tag:CprTwGDURumSTfPtnGxfUw==,type:str]
    DB_NAME: ENC[AES256_GCM,data:NecTVEmNGLw=,iv:D/JMxRaJfaWT/Ak5eLXnsMiUCJWy8rAdl4j/clRLCUU=,tag:0rWLxLtEb4WaSm4FkGYvjQ==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:+fT6t07iEzwJJJtogb8QHJQOUjEV0odlneIb3kYrJFY=,iv:apffWhtga7nclUM+Ylufzd3429L6hsiR0MYKTZgWAuc=,tag:MKygHnfuXQda7ef0vNOhDQ==,type:str]
    DB_PORT: ENC[AES256_GCM,data:o7e0w38L6iY=,iv:D/utGElPioFqdoojFQSHz1dmtwxJAV/MAjtC3hfKjx4=,tag:w/eJ4BNodKoUu7CjYdKihA==,type:str]
    DB_USER: ENC[AES256_GCM,data:bfeFim2ZGMaC4xv6,iv:mXkwDdOqKfXt17RiBfOLwiTeFQupkeVCvt0sNDVJK1g=,tag:BF3XK2+cr1akZLuU52q+xA==,type:str]
    TEST: ENC[AES256_GCM,data:SGF6+A==,iv:v+9y69dn7rtWzxu1knw8sr0VKv2jBnZUuiQynyrhgEU=,tag:H5aRZo0hIGkOXUSio51n3w==,type:str]
    TEST2: ENC[AES256_GCM,data:4VLHei75KfoNJidpcsv3Pg==,iv:yHfx2B6SHgRPni8uJBwT70lKqb25L45fIhN3eek6dIQ=,tag:CPKKTkELB4kU1gkOJYValQ==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:000000000000:alias/sops-secrets
          created_at: "2026-03-27T02:30:04Z"
          enc: NDY3MWE1YWYtNDRhOC00YzE1LTllYzgtZmRkNWFmNGI0ZDM5pScaNUQtWEmXNnScY6ffydmD+hL1M+x6bqGLA1na4HBRKFIRVdLd/DiB8Q+WXgbiBBLYB1Pa0Aogm/9Q6pz6SPgO3jsiCnTxL36uL94fNSM=
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-03-27T02:30:04Z"
    mac: ENC[AES256_GCM,data:Pi0j/y7MZ9k/tJgHglKRUWg6icJLe7+KnNYbWb29TMO4Cww+gmREKdYN0EfMHnvOxt0IpadF00xhxZ/lpQa111Ud6wsWARUSHmX5PMt4p4OvO4B5FNG9ipnFZ5BLfhWJPEl/ko6tgFWFSnHPnJ/kGcSUy6xAcLSk0XKQ9mPBvTY=,iv:frS+CC++NrwCdweBMaU1iS7CdH4XDkBomLeXns/by0A=,tag:wDcl4kGCttuZJdKK4F6xrw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.2
