apiVersion: ENC[AES256_GCM,data:g3E=,iv:oz1ACcc9zphtPPz1AZXpYM9eq5KO4sIGjfdMk1AjduY=,tag:9DfnPvYZ7JUYaPI3H0/9cA==,type:str]
kind: ENC[AES256_GCM,data:qHDZK77Q,iv:AfGLK9Q2jfjio8mXrvX4AQi6735v6dUgug2akl8SqM4=,tag:6nR45aTgPBdnCYK2NcquVQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:K0WQfKP7ZBSH/sKg/P8=,iv:EoJGEsosnP/YOyLfK8ttYNhtRl85DN9x3Q/3pd4258g=,tag:w0N9LCF/IbjocVI2+MsziA==,type:str]
    namespace: ENC[AES256_GCM,data:QQDQ6fSFLNqqGlU=,iv:ekx71FgJDkq4TBqpGP8Q/4SqGaAfKJxgKTb1xJpdsvM=,tag:xbSqHkXDWPEUwWntbh54JQ==,type:str]
type: ENC[AES256_GCM,data:a80mfHLD,iv:d0rjk/jpKsXu7HCpMEUseWitPDJK2GpiuW3HjFBg9nM=,tag:yzaerrJszQbhuUiNN0m8Tw==,type:str]
data:
    DB_HOST: ENC[AES256_GCM,data:elCEPJiDCSHFlrH3GCrURAuAgIsc17Jp0+jYEyb5gjOiQ9qot8st6A==,iv:s2bodxpIqsRe/xIl0oUOX0l14+66tolvl5XbSqMkXhc=,tag:pDeuaSKMEkBoJ3+hWOLBPQ==,type:str]
    DB_NAME: ENC[AES256_GCM,data:NORd4uNBLpU=,iv:HcUp1oTToDXOHj/rjbNiT/g8Ivyg+yyaFZCfCTMe0aY=,tag:35iqb3b41hFNSlG/9SuDMA==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:E+wLtpQJnYsC3iOHrcrnP6695TSyvbtMXb43KytLRp8=,iv:X1EggVOCZIsXgPFn+Z2beNg1UjvJJ+c9XXpLWGccZn4=,tag:dwGXjrXj3Z/2mbf9dVB7FA==,type:str]
    DB_PORT: ENC[AES256_GCM,data:jgTkJcOOR5Y=,iv:9BQ6ednBPmDA6MmEIfVmfKXMY2wKD75Cm5K4beEVVNY=,tag:GcmPb6TuvCpf/sn0rHb9Kw==,type:str]
    DB_USER: ENC[AES256_GCM,data:TcJ3oEBIk0VjX9PS,iv:0ySW0V6APY5u0WAX2jkz2Hhbrpqoz44Ayy2fzvFPBac=,tag:mcIR6cdw2FDPClqHq/gOCA==,type:str]
    TEST: ENC[AES256_GCM,data:n2w//Q==,iv:Gkmo6TxTAxHmny8HQ+4C3kunb+ZEDcWRBynFfFglnzg=,tag:XFzLpqKIGpd6xzdy0Kb7Uw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v0kj30lq3ms08909fvlw4s7d667l822tnjlrgq628hp6jrsdnvzsearc33
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2dCtLRUtnSW9XWkUyMDlz
            djhHQk9tWFlWbzRJN1M0SVdTQUIraTNhcENrCkpRUkVUL3l6VnkzcWh6Vkt5b3lQ
            RVRxbzJvWXd1bUFQQkg4bDM1MjNXT0UKLS0tIEF4MVAwb3lZVENOMHVTNTMvcWNq
            c011V1ZpMXVJckFsUEZUamZURmVWLzAKz2kBuMzT3+uDQ18wj3/TtcHixTmW8S7B
            q5mob33Lwlh2QBHLFCVbWOvR+AqDfk4LqxQlbYmIbQYjnn7qV0F0SA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-25T01:58:32Z"
    mac: ENC[AES256_GCM,data:EPKgWcPYLHoKkDkf0cQyhkWtiQvJktuWnZFFLdPAVkdAn4zWu3CkqbQdEA3k9fiVc4ojvTiYMLdHYTALvuh6h4Bodmy6mLkSsZD4udi1gaT8fDWOby01aOngwBhieGanCT6465lUATAHhIVxZcKkdTLFy4ZSEz3xVgh48Oxl5ZE=,iv:QNCsZi8oqXuBmniTDIO1sp1HTyKg6bQE0h49WGH6mY0=,tag:w+0SJdMI3zXDEfVol4oh8A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
