apiVersion: ENC[AES256_GCM,data:es0=,iv:y3GckPmibgiv9iIxJ1L1CLLu4PWvD4FhRz3x1ZNNrXw=,tag:53aMvorpQ5pqG3oJfY/MjA==,type:str]
kind: ENC[AES256_GCM,data:yfasaHdb,iv:zKRObaTNZf3OMuBoLr4bd8S+ad2hKjfmvApsmAJINcQ=,tag:p8iXpveXGHxxpRbvxTs5Jg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Ibk7X0u6xEZKEy0FFFA=,iv:FdysKCLgWwTFdJnxlv817cTk/Ptn4WfbEcY94Rfa4BM=,tag:OkJr95FkrIkkl8+RKH5KIg==,type:str]
    namespace: ENC[AES256_GCM,data:+E+6/SWWcHg6eXI=,iv:DEfrPn/Xe/IUYe2gNkLALwJQecQnrhPKyK4xT9T1rDk=,tag:w+akVKOT3EV4IuEKNsXEjA==,type:str]
type: ENC[AES256_GCM,data:5zZziHXX,iv:RWvMUZXoGE7cif9A5iFaLzusBWlSnx/Uy1phsq9Gtpw=,tag:8maDhuYY2fnIMPrZFMsRZw==,type:str]
data:
    DB_HOST: ENC[AES256_GCM,data:i2jwcov6X6YJIqFfgDk4e1t4ZbLb9zMXzDfDkBPyZclJSDryj32xbg==,iv:FjRVuVml0YYo1+2P1Ry6PWJPYqfnjQ/2Ph24NfiFnZQ=,tag:HoETdHPKIkoz6NQcMUP1xg==,type:str]
    DB_NAME: ENC[AES256_GCM,data:4xBloozsGmA=,iv:xy6rIbfzwPlgE0Pd5L/mvNONL+ITwsGUlWRGl++svs0=,tag:LcAfLhscauqR+Wjqd2rNgw==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:TvDZpS08DhYzyAuUXK6SUHOG8G9/OBziSMRb5oVH7GQ=,iv:79gvhEvWcAcMAkRBTS7h++myYz91dH5mVfleJodeLUo=,tag:cs1tSIA9hN7BY0Ga13Wp7g==,type:str]
    DB_PORT: ENC[AES256_GCM,data:oylfRQ7ecMM=,iv:pFDUW3ra2U63/2MjLBLYyBmnCE4gF9DaLkww5yRFmng=,tag:C9lcJs1JVBJP5LtWEUiZdg==,type:str]
    DB_USER: ENC[AES256_GCM,data:g5R1gZFMSGnhBv6v,iv:GFAWUfPpWfC3wYUy0CjP2RPNapi6oyW3Vs0AEQVCP+8=,tag:BSE0KjFpQTE6Fs0wCIcvAw==,type:str]
    TEST: ENC[AES256_GCM,data:xN40LA==,iv:aBQ2FUDsscBkMdRUowf/ebB5+456Iaag+VCgmx1e+T8=,tag:/CEPm2BRlQWvIz1oML519g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v0kj30lq3ms08909fvlw4s7d667l822tnjlrgq628hp6jrsdnvzsearc33
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzUGQyTzNmRWNlcDZBdUpw
            NnpLNGtFeDZkdnFLSVB2emJyQkZmaVlWeUJBCktBYUxhMHozU3VwTTdkUldjWk12
            bGp0RmpsUDM5c3B6RXRjenVRdlNlbnMKLS0tIDF6Y3B3VkVpWmVUWVA2VGVZSTA4
            ZVNrWDRFV2xjSHEveHE3aGdiZ1p4ZFUKbytg1mY6qU5Mqcu2J0AYudj2Z2qI082J
            Isn+Ijiv+raYwUFpAV7RAsAEj7hqtTxqAi0VtXscBaH7F9sNMk0EHQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-25T02:46:34Z"
    mac: ENC[AES256_GCM,data:M/UwSmFosxHE/L8L9JjY+XU9yiNjkc8atUPmHWXLFt6IwIFlkG4dhWjS1rydZy+hXumDnaRBF6zjLD0jlLWfVuYb4Sr5u1q9IwuVvPORoaxL3uF2etH5lsAhNKvs0gI+PT2413rBOW9PydrRIyA0E7w/hVG7zDz1ayfkCi41n24=,iv:/rUjOpKve9hm7yRUGFzYJue+qc+n574j7sN34uLax3M=,tag:SrJ+t9uKJOTdNABjM0jkCQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
