apiVersion: ENC[AES256_GCM,data:YlE=,iv:RdRY8bNWpwe1qxl8V92JELKMoBIyVW245OrmE1LpmNk=,tag:iQq77gn3wPAGu3XSRXhakg==,type:str]
kind: ENC[AES256_GCM,data:Cj5b82wZ,iv:Qc3VFpAZgefX8fcVjB/EW8Re/92+wBKhWoYuMbyYjzk=,tag:3XXMl5g6yjLhNkDq5W21Gw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:5iabI6Nq+64+,iv:lK/A9K97YQZzaNMZNerliovKlLgNz/cslNr3/oBLaxY=,tag:qyEyfpVykovuQMNl0daAnQ==,type:str]
    namespace: ENC[AES256_GCM,data:5HEOaxut0PvbDXM=,iv:qqQdePVQvlxlmz2Yrnth6Ozg0UjVTRpbbFnDWSlZvnk=,tag:S3H7dCHiPpOLXStB7SqLig==,type:str]
type: ENC[AES256_GCM,data:xZGE32FN,iv:1ECEH+ku6InMRXiUQOigBxJgPWjk1zE2jHCvxDJyQ50=,tag:LHVXxQGPJPDfAeU9LbBPyw==,type:str]
data:
    TESTKEY1: ENC[AES256_GCM,data:aTyf0Bx8s/sERR2L9b9EMKGhAM+NIlVP,iv:KCbB8p4Kx5VKI1QUSBPF6t6bdIGPfey7ZwShU/gB8rE=,tag:URmAbM6Pzv7a2EhkTy5Usg==,type:str]
    TESTKEY2: ENC[AES256_GCM,data:+ny/+zQ0U5cbIOcEUohC+J9vXaUG1/Vd,iv:NhVR6Vb83RIXQJr1Znbxx1h9RYD+wAnLGCHinP1tXbA=,tag:s4Zw52GtNAUGRAGAJPpMsA==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:000000000000:alias/sops-secrets
          created_at: "2026-03-27T02:30:10Z"
          enc: NDY3MWE1YWYtNDRhOC00YzE1LTllYzgtZmRkNWFmNGI0ZDM5fgu1iK5wvXoc+LcyGLpQItKQY89ckAYrTkmcYhVxtaOWWqvLrxVGHbuThl7K7jT00pDPnHgWYfuY5gd+i9g3aLhhKHOLdMAwF/2w+zHquXQ=
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-03-27T02:30:10Z"
    mac: ENC[AES256_GCM,data:Lfjg9U0UAqCXVHUWLYJUpbMwdCrKM4s1+SVJevvdnpDT6VKMPvwssKeocjPZRUAPeXeYs1BXTxZaVErZ9BRH6a/jt802j6EvVmsTsUyxD4rEF1w2Fj0fd5U70bEKWvMN0y9GuNK/DpLf6L7BT6gNKTuXgZ9n0UQXhUXFkMcrONw=,iv:UFqYozhnupd492IVDSoaa3Icq3h/xeIbQ2um/e/h99c=,tag:M3awpDjK6ctBdeJTD6ZYGw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.2
