apiVersion: ENC[AES256_GCM,data:pe0=,iv:IvwgnpOeFhFPGE+lMTQuqv26BPOEMw/cwW2gJYMFJbo=,tag:E1KqmskujYT+PgCUAjwefw==,type:str]
kind: ENC[AES256_GCM,data:wq4MnviR,iv:JKju60hhq9X0QmdIUnKX2urqMaObIuUELVIkMWPL93Q=,tag:n/gbOeDuva5MXEJXMbP8Mg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:XltKDVNrfZLw,iv:PN2XNqHVdfK36TRdcrI/ViAyq6FPkIGql+da4M6wsPU=,tag:9YIyTnSkPYxN7zzv4SEX/Q==,type:str]
    namespace: ENC[AES256_GCM,data:n3b96AEGsWTe52M=,iv:ZaWLinWQLhPhFISK8JERxBJygzggsOnIAgdCDiCwEaM=,tag:7Fl/rEJkwbc2M1lThE/Yqw==,type:str]
type: ENC[AES256_GCM,data:E3TMnTBt,iv:b5Vz1S2hrWPbTDmX1IdWQ1VJ6RtmAud47gMEdBc4tek=,tag:Eyg8GJ+RoIXRNugu3pJUrQ==,type:str]
data:
    TESTKEY1: ENC[AES256_GCM,data:jQP6g/3fSxAYGqRGmZEWFbIFpqzDsuKt,iv:fJVR9o3Y0f5ddpUfKIKm/rpzsQa+++r5L42ClV2JkoI=,tag:dCNjCjxlrww96qkZ1H9kTQ==,type:str]
    TESTKEY2: ENC[AES256_GCM,data:utC5WzGZ1+nmIPQG2LljZaCJNGhdvbA7,iv:lFmoIKIOUIbfMNKH2uNI4UuLIPm0zwfUDbv7XA1QwjY=,tag:VxSjL1LtlNOX8D7cPguXgw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v0kj30lq3ms08909fvlw4s7d667l822tnjlrgq628hp6jrsdnvzsearc33
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQbDIxMXVyNGlSTExXYXhl
            dS8vTTlNc0YvVVJPbmZIS3dCMDdVM1BpMmdrCjk1SnFYTDNhM3Y0SnVPbGpmUGZJ
            ZTdhL2FNcU1ZWU9UVHdrTWV2QVF4TXcKLS0tIDdpRlRTM2lmRFJwNHdnYVI2Wml6
            OTFkM1U4cUFGdjkwTG5qTGdEYmxmYzQKvRBZKURBF++voSv6l1pQSJoRpkXTDHTU
            PU6OYuxh3WU1QgwuNoSf6FURszpssdTeZZjioJG41GLbs79gXT46TA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-26T23:29:47Z"
    mac: ENC[AES256_GCM,data:M2KLEGieZWhQUwNNxzTYRHMYWifuQKGyA67o6GDff/lcf9vzT3Y3ScrQssJpQ7cTOwjOvaiH8VqfdaFfRTwvgSXdw0tNU1ODUiRK/NMjxTKqViuxDCOrlzwZMlOC68orA0hBWoPa29pFaFu2y8BMUYY+GpQ5ecnzVi3Y1OM5H6g=,iv:rwaEXfWDLV5wVLvMXtzG9mvwrIV4vU1iALrJTSRZ/B0=,tag:zlGzAbVHXkl/tnZ3ayPtwg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
