apiVersion: ENC[AES256_GCM,data:pe0=,iv:IvwgnpOeFhFPGE+lMTQuqv26BPOEMw/cwW2gJYMFJbo=,tag:E1KqmskujYT+PgCUAjwefw==,type:str]
kind: ENC[AES256_GCM,data:wq4MnviR,iv:JKju60hhq9X0QmdIUnKX2urqMaObIuUELVIkMWPL93Q=,tag:n/gbOeDuva5MXEJXMbP8Mg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:XltKDVNrfZLw,iv:PN2XNqHVdfK36TRdcrI/ViAyq6FPkIGql+da4M6wsPU=,tag:9YIyTnSkPYxN7zzv4SEX/Q==,type:str]
    namespace: ENC[AES256_GCM,data:n3b96AEGsWTe52M=,iv:ZaWLinWQLhPhFISK8JERxBJygzggsOnIAgdCDiCwEaM=,tag:7Fl/rEJkwbc2M1lThE/Yqw==,type:str]
type: ENC[AES256_GCM,data:E3TMnTBt,iv:b5Vz1S2hrWPbTDmX1IdWQ1VJ6RtmAud47gMEdBc4tek=,tag:Eyg8GJ+RoIXRNugu3pJUrQ==,type:str]
data:
    TESTKEY1: ENC[AES256_GCM,data:jQP6g/3fSxAYGqRGmZEWFbIFpqzDsuKt,iv:fJVR9o3Y0f5ddpUfKIKm/rpzsQa+++r5L42ClV2JkoI=,tag:dCNjCjxlrww96qkZ1H9kTQ==,type:str]
    TESTKEY2: ENC[AES256_GCM,data:utC5WzGZ1+nmIPQG2LljZaCJNGhdvbA7,iv:lFmoIKIOUIbfMNKH2uNI4UuLIPm0zwfUDbv7XA1QwjY=,tag:VxSjL1LtlNOX8D7cPguXgw==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:000000000000:key/9393e8b2-6930-4ff2-a038-8a2ca1f3b747
          created_at: "2026-03-27T01:25:38Z"
          enc: OTM5M2U4YjItNjkzMC00ZmYyLWEwMzgtOGEyY2ExZjNiNzQ34ntbvIbrQAMcLjs55uhzjcOAaCXagRugrVMXdUhYg6rzz8Wir08Ywq7aDJ1N+x7YkMtSHetd7vWQb24a304c/DZ+I5+9u3H4JCSjAYECtE8=
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-03-26T23:29:47Z"
    mac: ENC[AES256_GCM,data:M2KLEGieZWhQUwNNxzTYRHMYWifuQKGyA67o6GDff/lcf9vzT3Y3ScrQssJpQ7cTOwjOvaiH8VqfdaFfRTwvgSXdw0tNU1ODUiRK/NMjxTKqViuxDCOrlzwZMlOC68orA0hBWoPa29pFaFu2y8BMUYY+GpQ5ecnzVi3Y1OM5H6g=,iv:rwaEXfWDLV5wVLvMXtzG9mvwrIV4vU1iALrJTSRZ/B0=,tag:zlGzAbVHXkl/tnZ3ayPtwg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
