apiVersion: v1
kind: Secret
metadata:
    name: test-secret-final
    namespace: development
type: Opaque
data:
    api_key: ENC[AES256_GCM,data:XdmLmK2euH9AUj7kzZq6Bb/GzW4=,iv:dJolqHaEnU1xf4viBAZpv/pcRq/CbDDwUUApAuzaPSk=,tag:SLBizaQJTc1d2go85u2QdQ==,type:str]
    password: ENC[AES256_GCM,data:LMTd8MQDxz9dJNt0Fdv/3O/n1Cg=,iv:uQUy1qulkNNhoh51tPIToN1+4Pr9oCO7YsYQwcMxbXs=,tag:tyG6/wrkfnlkCIHMnHwGJQ==,type:str]
    username: ENC[AES256_GCM,data:A/6hhNqNsv3Mx9AV,iv:3QeGMeoDxOcjpBoMemewzPyPdtP8DAyCfyJRTnWGjSU=,tag:48ECjafI7/akwZf8VGcqtg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v0kj30lq3ms08909fvlw4s7d667l822tnjlrgq628hp6jrsdnvzsearc33
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0Y3RTVkJGTUk5QklDb2tq
            NGRZMEREbVB4ZG5MNnlDVTNRYTA1VGYxd3c0ClRkNGgzZ3BXclc4UTRjL2xndHpi
            eHZkN0pRRVI3WVVKYnd3Wlo3OWNxV3MKLS0tIHg3TWZ1RVlmaTd3ZDlPREtMS0cz
            WVlZY0lzNWNxbkFURGp0a0RuanZPRDQKRfJQwl7T7kqMGOwKMs9LsYVt/Bk/LFLN
            yEIfXWff75aLSKJ8OEehIy/y2W4u5T9wt2YYfKWy1Wr1Rx6DVz0xww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-24T22:21:30Z"
    mac: ENC[AES256_GCM,data:s+3FnalBCLb6J8g+PTIJ00ZR6GtcWZr83y5NZrY2lJKRm/SNIeEm62rWYI06RQc98csYy/n4yWYcxPRvDbDowFF/KDGWMolzAWfaVorX9fNz+p4B6kGh0Hrl8cTur6tJiR98NE3zk17+1N7nYiKGhdCqyXQJJf456JPkddLJJTA=,iv:7YLK95kuDjMxw+UUT/EQR8aQoH5pHC9yPp1TOYeV28s=,tag:BaRV6jcj89mFdpf79FQXBQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
