apiVersion: v1
kind: Secret
metadata:
    name: test-secret-e2e
    namespace: development
type: Opaque
data:
    api_key: ENC[AES256_GCM,data:YDh48/C/CtRpXaVhERc8Ph54KcR73gvo,iv:pOaxuZnHIf5Eec55onvwae2LB2Z85ruKdPBCQXNZsaQ=,tag:OGsvh00eaC079/w9w2a+Wg==,type:str]
    password: ENC[AES256_GCM,data:QvxTmtHwaYziAf9JJ7K7z/S7V88=,iv:ps7d/BP/VaYU7Sc0f/XglwVWn5Pkh3KRAHU0q5Hman8=,tag:nTr0llxCdQCl5UsH+bqcfw==,type:str]
    username: ENC[AES256_GCM,data:xIvZwUh3Os+Xn6gg1k2ymw==,iv:+D1HskZfabak+5Pu2YyL+On0Vqg2TDRrd4d5axQNur0=,tag:WnsQRYka/nolSMmXIPbgdw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v0kj30lq3ms08909fvlw4s7d667l822tnjlrgq628hp6jrsdnvzsearc33
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4RmRJTG16WWZmRUY4OE9I
            dU1LcmpEVmVmcmNmQWV5YXJxc0owOEhldFVnCmJCVDdvOUVNUFluaXRETS83UEhO
            OEZJVHM4NkgrMUQ1bm5sWWNIZEFoN2sKLS0tIE1yOVpQcDVMbWxVYThKblQ0VEN6
            QklCd1pBQlhUSm1sdUlyUTV5alQyOUEKMG0i0R7tMgjLwIUcPhFmqAnditS/J6/1
            TAouTtz32/K9id16NCVHpXOqCsu9JkkXDIdqmsCPLjxURGR/+sM4HA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-23T01:12:54Z"
    mac: ENC[AES256_GCM,data:q6oqN1m0vhtx5zxHxOCjhgCYJGBaOZt0M5IDnwv1HvbE5OzbwahwW6goT+RWK0NwQWAyeu8BVdsRr52KIdJ+TImPD4OHsAcy5mtTzUvc/nSYDdPWWnJw3oJMoIDagrVOWRnqmbcL47J64j/j7bG04mVAEf95UUKLgZXMqpUva2Q=,iv:0FsKX2dcQn0RCLVga56bYOrHIo4nTFEjRuyGJiMKDqs=,tag:Nw/TyiaTyDoqOzAxDPuluA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
