apiVersion: ENC[AES256_GCM,data:Wqg=,iv:AYL6iDR8+421xxx8sec6N4QvFySLNPgbaBiOTH5shEM=,tag:SrA+8UFjDVBfw7eR56R9ZQ==,type:str]
kind: ENC[AES256_GCM,data:a51lRy/G,iv:9BbGizOGivDyuMlLPGmkMFJcjqksT1X0urN50RPrAhQ=,tag:DIkoNsPmsw3SMb1Cv1j22A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:f1rr4sgPU1J0GKDEj8XD9j4=,iv:eX9Aevi6nXsW1boNrpek12ndsXIfmIsg1bVdJfiX4U8=,tag:ds2yP5zJjk4Zo8al+HoZdg==,type:str]
    namespace: ENC[AES256_GCM,data:zUsKUuHxarXFoaE=,iv:Wp3we4YmeDVlpaa5/B05w4rbYq/9mvyJ1UebHJ73zzU=,tag:puSwZ9GojTABIFNrqMTbFg==,type:str]
type: ENC[AES256_GCM,data:UT6tEDyD,iv:vO5PSOZ4zMr4QnCvpm+bbRBuciPX5OQwcxKcZl3ZdoU=,tag:CsUgSIWDEawE8PSz59EF1Q==,type:str]
data:
    api_key: ENC[AES256_GCM,data:MWKGvIPbwFENkRsUmrOzzdxWAJ8o6RkVRvuC8g==,iv:CmHnPYdOhnFVdA44pBsPSlSOZBdCbrXoDtuLjiiMU/w=,tag:GGhpzEF5Xr8XbK/khza3og==,type:str]
    hello: ENC[AES256_GCM,data:R8PI3synDdoxfT9dXrlU2g==,iv:UTmE6dLA1je2+otamikllRvw3JGUplWvHhPk0WdmpJM=,tag:C2ynJHtZUV5s7ZGfKUAsQA==,type:str]
    password: ENC[AES256_GCM,data:MfYIY8mepA8mPrSL6wknFCMfMR1JLyobbhh5kA==,iv:yzt7/6X4TeBH/n7o7PjZPetP+AeXJ+8fa366YEZ7WNw=,tag:V7OeeD6Pcl1rpr2tcamMWw==,type:str]
    test: ENC[AES256_GCM,data:rwryU1H/vNg=,iv:enTy4IPiKIUv9xsaTM+W5bQXZ5PK3g6EMoz3dE957Qc=,tag:Ur1kExe4tHFoWWkHKaM+Tg==,type:str]
    username: ENC[AES256_GCM,data:Grf8ZtkAe1Kn+VM5CeLJ4Q==,iv:o0ct8GtSqf8Mt5fjIXiNniZqhctvqTHto6c3DAv36Lk=,tag:VnvhYJAd8aU/9Xa+FE+r8A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v0kj30lq3ms08909fvlw4s7d667l822tnjlrgq628hp6jrsdnvzsearc33
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHSGhhOGpoZkloVlpzbEpk
            N0pHaGlQa1BYV0dhQUFlSERsWFFwUld1Y0F3CnNoNmZaS0paaisrYzNJMnRwalBO
            QjVQVFlONVVnWVl5SkFUcnZKTnlZSGsKLS0tIE9Pbk16Y0s1dmpYNDY0RVFSdzFl
            TXVjcGhXM2paSGpKTi85SnRNdlkwK3cKWnmXt1OjSzmUbHZt/Gana6rIN/imc0pw
            To8nCPOmG56fMNsD4+MucJquSQuJqONGBaPyONt/WYBl9DhphNetpw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-26T22:16:57Z"
    mac: ENC[AES256_GCM,data:or2ZnB+rptac1BYWMP8/wjoJwFMG64v8/DSwrdRIwDOQluwTOYC1EA7HDSFZzXQLdizh5htDSiw+RkR0/JtZD1B7vnqraLl480fKJUAPdsuUgkSQcZqzsS0WmFT1yyhAaQ8cjNz59Qy51T2a0gMO1GqXUhBxXs7C6BAoPv3tG3U=,iv:5t/vCmDD8x9a0r8OT2wotYJ3wahVlLyRkyO9qUYPRVI=,tag:4lMlrKQZB81POUciDp3sdQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
