apiVersion: ENC[AES256_GCM,data:ji0=,iv:sO4aNSPJumQrCQWL/NtbKXDZMVYwWXKrX38u/IrIK6s=,tag:ckk51zXIfRhk1mrJJW4yKw==,type:str]
kind: ENC[AES256_GCM,data:3j8paO5y,iv:ktPMVU9fk6pHDfIEh8IGPzd3sRzhBfPvUpd2lT4+Yyk=,tag:wJs60JSWqFyVSVqg14BWrA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:vw3P1QFWeNTOVV0uBYGT,iv:2goCcd6SvR20sVXD+QIGG1gt8N247xKoGc06r/66Qdc=,tag:4S5XS2t1xqoKhcQsYANeXw==,type:str]
    namespace: ENC[AES256_GCM,data:dquLi+056vTV9gU=,iv:Pq5bAhi8KOfNq8d2q3HJrnMay4ab5iynE1rE+mRwds0=,tag:6DYUI5NiqZ7GvJyNaNoHwA==,type:str]
type: ENC[AES256_GCM,data:hSCr1ZnI,iv:3M0hBevYrJKF7FDvjgpeUIY5QdefDC6cv5staZZTI7U=,tag:sZFekRYe0ITP9zXyCseZ7w==,type:str]
data:
    api_key: ENC[AES256_GCM,data:Nq0LxLTWka7j55SVus4XbAiBjMUmMUZn,iv:XVAm1yhAZwvoKwXFlBnSInZOTI1lPVmYOOiCnY/nCss=,tag:B99gfJgCSSqIO/3yvB4P8g==,type:str]
    password: ENC[AES256_GCM,data:VnwItVlAX1PpC9NG8iS/L7Dl8l0=,iv:SnC/HaF4jr7npovpgCO2MRY8HIpuknFD+ratoYQglcs=,tag:flYyZwYbJq3c0CyULndF6w==,type:str]
    username: ENC[AES256_GCM,data:lcbSIQ9zUxIOBa5mrnNkSw==,iv:uF2H8osduZYk7zc1tNNJ72TNcjTOB2xqIcEhgJEMA+4=,tag:Repk7XbHOv1/ATqHXQwj7A==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:000000000000:alias/sops-secrets
          created_at: "2026-03-27T02:36:10Z"
          enc: NDY3MWE1YWYtNDRhOC00YzE1LTllYzgtZmRkNWFmNGI0ZDM5xPqCMIwMZ2ZKVBErLC3+6GOwlXuw+vPGHdyfwQnlUgKRz0jmZ2+UTdEKEcHffuYnWeyZ/n0MlI+BEmBW7YD48aVSO0WQgbxkLi8xWRsCPtU=
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v0kj30lq3ms08909fvlw4s7d667l822tnjlrgq628hp6jrsdnvzsearc33
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJR3J0VTh1ZzgzSk1XeEJJ
            LytHZUxmUkI0WU1CSldZTjV0NFVQR3RPRFdZCkVaUjNpQUtRWllDNVA3dG5jRWVP
            OTVQbThZdUpSWUp3Y1kzTTI1aHY1cUEKLS0tIGh5TERTZ056UjNLdnYxVUhUWTRR
            TDhvSlZHYXJyU1MwYkZuQVp2WXJud28KDEKiIacU5ncEPhOn1f07ByI3tRx4OTFl
            RtxPe/fcGCZHA6R/9taqDuIjwg80MP36tciaIa28Mcf0b0q7jWstZQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-27T02:30:16Z"
    mac: ENC[AES256_GCM,data:nK3kddNWZJWoyswjWNpZiBWkAre4GMKLbuF8atj+dz2VentYGsyc4HeQEXMIfINrDs78D7u+q/CXSpaegKol3jWjLGtKxN+QkRlmKgDS0VfI8ngnEfZfKrqSAfzaqGlz3u7Gyx1Z5BFwcZvAF+3ZL8XfUaK6hzRJvEkiCs63LaM=,iv:SzDEI7iOCZx7NUXuLZOmobCC8qhOeZTVN4nXfMWX+CY=,tag:gZ9USk6u+Ka08aNlZfNvfA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.2
