apiVersion: ENC[AES256_GCM,data:9+g=,iv:QpC2hwIXX9Bqtd1p29WrzGDOHozSpwroPHauxAyHlQk=,tag:fcQhv70Zjqctn0cAenhg4Q==,type:str]
kind: ENC[AES256_GCM,data:V6k17ikU,iv:4GRO8v/LPkq7wcJbzkkzjo46payse69RoKkv5vUcTHg=,tag:xrL4LCCcwVorVGw0AHXUaA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:alxxYjzULx0/RtFqrMq0,iv:xOut/vQD56/t/Lu+deiLKhoY/OvpESt78EWY83k1pjk=,tag:rgOV0wFULSu45cTx0Jfn8w==,type:str]
    namespace: ENC[AES256_GCM,data:2y4OqnmT00pEVJ0=,iv:WxgnI7Ky/Yd8qpfikPlIOncGf+HioH3V8sIIkuE+xV4=,tag:WK5lw/pwjwAIMWsFyIRjAA==,type:str]
type: ENC[AES256_GCM,data:L4jpBsDt,iv:dbmqWXPw1ufgoNmdHJC8BRZmq28V1wABFSNgImfl/cw=,tag:hLlXsoBd5hwRs0sNuD1hQA==,type:str]
data:
    api_key: ENC[AES256_GCM,data:x6sjWHQfIzEseh6Dv2N/QpclCNRd+dEB,iv:fCw+SAmGX/pIr2b3NVgILZmlW1Fvxt0tJ/t4SUGGuS4=,tag:lYFAGFepIybxO2r/1+z/vg==,type:str]
    password: ENC[AES256_GCM,data:44SX7AlfA3z5FtTwxEM3Sna0OoI=,iv:L2bQHDrWgDA6uXKdmsBEDr7/JWLtGtQojd06jo5czAU=,tag:M/PXcEd/0pF9bX2lyMNz5A==,type:str]
    username: ENC[AES256_GCM,data:XgvgTGQQJCqY7jrywBlNNQ==,iv:FjV9f3WrQjQkuRYJUxI0h4nsW5aC+uu4MBrlT2M/RHM=,tag:RZGt1Glu/gwTicFqHmstuQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v0kj30lq3ms08909fvlw4s7d667l822tnjlrgq628hp6jrsdnvzsearc33
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1YUJudG43ZzhFengraGhW
            ekFYdGNualRJeDdkbUVCbkpEWVdHSVZsOGtrCmFJMnZ1OUxtSWNSRTZLUU1jQ28x
            NnBwNW9wUGRqbUtPT3lLR0dGU01WSVEKLS0tIERtOEk3djhXQmpubGZFU1ZnUng5
            SzFFUGljbTlQVTFYNisxU2hCTEZ2RkUKWzFRZhST80MYbHELuDb6R6xRBPxO61xp
            QgLn+h6iC2cL2mg6SlV0qCr5O+vFnvMcF43tcopo3CfADJ/LljVn0A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-25T02:43:52Z"
    mac: ENC[AES256_GCM,data:1af3HZ5VsnOWSDFFRwz/43S8vG9Pj8KYO6ie/FrVWD9GVsW4m2qjiapbBsk472QEP+GsUeCjQA7z2NaOndbMQ1YsbYMG8cilRADeYmQ+WOD291rhY4fTvJ61q5nLeMlY4uHRQsAyJA5b3Zg90MLj3d3bFSF3w4l7vCFz4FCd0Oc=,iv:iXqrVJGYv3YDmW5Vwg84ccr65TBUQVVfw82DLa0SuzI=,tag:wHH7oTNMG4/TAL9mLIhXCw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
