apiVersion: v1
kind: Secret
metadata:
    name: test-secret-final
    namespace: development
type: Opaque
data:
    api_key: ENC[AES256_GCM,data:QIyrd4pvRT0Q5hzaSMARVrc8f/8=,iv:UyAXXZ+Oqptz921+EDZHLvYBnQcw70f9DDBQwkG8Yrs=,tag:AVynPwCuLEODEgxVH+h+jw==,type:str]
    hello: ENC[AES256_GCM,data:JdM7ArpBwNUn+PZu,iv:L0iOpcXPqCbksqk3IvKEG8US7mRTjvIxOfAHlWahxb0=,tag:zDEVgpOvYbE3x2CN6Ndd4Q==,type:str]
    password: ENC[AES256_GCM,data:6ZEm6/tjKe6/PhR1WNvDL0JIB/s=,iv:ok2MrLs6t0AeiEmo5mQkjrB8JlKpuIj/wIfDRN359f8=,tag:RsZlmeC8mvhyepvqxjriow==,type:str]
    test: ENC[AES256_GCM,data:MJNx0Q==,iv:JfkIauPqH3pwKXf6oeLodCafXH1OZXDIeuONbbTzDgM=,tag:5Ted9HgHMVoeJZKAln47nA==,type:str]
    username: ENC[AES256_GCM,data:+dCbGEXYbhX/tX7t,iv:D+q6gXO5nNtSOCrvEbWhhHghgVv2G7TawXXVaZSXArQ=,tag:6vQARiMJmfpDCXDIqsXQpQ==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:000000000000:key/9393e8b2-6930-4ff2-a038-8a2ca1f3b747
          created_at: "2026-03-27T01:25:31Z"
          enc: OTM5M2U4YjItNjkzMC00ZmYyLWEwMzgtOGEyY2ExZjNiNzQ3/YCUJc3byWlR844JedTNwjsVN8dpYryiBJJSoQdtBM9Jyr/d7RZVhHr0tvoXPbqMO4/KjEfnT3X36WZiKb5DAWF/v6R3nzW3B985jCdA6sA=
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-03-26T22:44:22Z"
    mac: ENC[AES256_GCM,data:EviHKXradgwpNZ57jmMzWUvRON38epb82WnH9RYfFwjkCVaUENjroXk5tcdNRvcsvR75Er1NGnXA7uOtF2N6A2vqi8xm3bnlJaFxXML8c8mU9PKgIeKnUHvfI27Vpx9ZcNox6hrQ16G4DgLH5a9I9DaUnhBRy2BTO8jlcBAM+iw=,iv:FCbFaKyGrtAycWenqyxTnZKx2zDunc98L5KNaQvc2SM=,tag:FLQqL0aFKHxz+POwuH6xcA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
