apiVersion: ENC[AES256_GCM,data:+60=,iv:4k18/xhF625fMQtdOsALRUWdmUH9R4o3WrrQUeL6d9o=,tag:n2IoOPESbw2erlBlY2z6vQ==,type:str]
kind: ENC[AES256_GCM,data:+LDFENlN,iv:5OrL2hla9jyw64gZc5OiY6+jjIFalb5fPMDwzMWjjfQ=,tag:WRsIkDq+hViKyOWTxotJIQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:gFJ8NTu+ks14b1c=,iv:7nOE2oh0ig3Zb7HbUtBTQXw0wb13jdzOdT6DG+DcGDY=,tag:A4KTgPr5zcetVyZO99XIIw==,type:str]
    namespace: ENC[AES256_GCM,data:C9G70sgz9n9e1SCr,iv:tHZJo2nSO4m49ZBZ/3C/Kv+ofgvvGO507mVmmbQ4NBg=,tag:p1hXF/W7IgkCj9TrXGrxnQ==,type:str]
type: ENC[AES256_GCM,data:HgN/xgqs,iv:+Tqh1gVn2/PoV1bTVAWluU1go2oAG5bQLZo3R1xH6Mo=,tag:1m0RL5IoQ7osZLgvneANjg==,type:str]
data:
    KEY1: ENC[AES256_GCM,data:LB+81VceSMTQoZUx,iv:q73PcRoMU3TNZBsfs0pirlAFZ0ArEA/dmpVzzg83pCo=,tag:6iNv0nyO+AGlJKslimz82A==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:000000000000:alias/sops-secrets
          created_at: "2026-03-28T02:23:32Z"
          enc: MTU1YTljMzktZWJiZi00N2E0LTg4YWMtOWEwNmYyYWYyMGNi7StOvf4JoWFkHu9NHTeMhiEt8BR56YqiKMz5qNVnKuYR5fU1fh4LbBL2vzCWwVN6Lhx77tPUcl6uaJvQms4DK38+EcMy5TF4j0IZiFLmhdE=
          aws_profile: ""
    lastmodified: "2026-03-28T02:23:32Z"
    mac: ENC[AES256_GCM,data:fdZrLgWgXHVXJPuiLnZKSdRIC3ld67euW5mpKv6Ck7LDU5NMWKF3xV4lELrV1JBEWsC3E1y1/qwdny1qFkrNixf8YoVzR/ZTF1tlrKLeBCY7TJdhYbEtQb4BOkOEZu/Fnh5/h+Dmb+OhI8EvgUkTYS/b+ON0RRbtGxrpZvnSCDw=,iv:QPDlr8gM5JAFOsfLqTDpkKD0msR/2p8L93CMmKA8qLM=,tag:lu5CfLO8lonGBI4fnIcSFQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
