apiVersion: v1
kind: Secret
metadata:
    name: test-secret
    namespace: individuales
type: Opaque
data:
    KEY1: ENC[AES256_GCM,data:nc4FPettnUhNFZqXA7KCmQ==,iv:2AdX4s84ZLsZaNvHMy5pnLvJgWRcH9glJZc4BQMJZx8=,tag:eoOR64HOqRSQtVSmCMcibg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v0kj30lq3ms08909fvlw4s7d667l822tnjlrgq628hp6jrsdnvzsearc33
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYVGNsMmMxc2FMQkVJempw
            dHdqVzBCeTB4UTBCQ0lvYjVrdVZWRXE5ZDBFClM5b0VLOXRJYWJHWWFLdjBsYktI
            WHZZNmVBWHB2NklqTmtOeCs3K2lNWE0KLS0tIGhrQ2YvV0NxY2F5RmpkaGtkaE91
            NmRnRnFSTXEzUVkvOEJnTVRGMmtRc2MKAIFQs3gnv/LHZtbdrA68kWHJUE4GXKNF
            28FWrg6U1/8vvcvwS0uhQQcKXMWkWb9msiU4zw+qM9w1DiFmk2O1dA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-28T02:42:56Z"
    mac: ENC[AES256_GCM,data:im4oGObU2/JPsP8HgkntOtbRVxW4UQ2Egi/LbwMrMeoRZlDgB324ZxG1p7o3YoPAbXlELUNxXdUxNMl2Pdmedc2lVlVoTn2Ocax00LapXyxFuVvVP9z3TuThKHyazlZI4wI9v/XbmnxrPL4juSLDd/jlrFEN4EYTLphn5loXkgk=,iv:Ej23QbYdowVsvfg/47MmvuqjW3RhUyumcmF5k0wN5OY=,tag:KEVwiIOvLl046ULuCrZDjw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
